---
commitizen:
  change_type_map:
    feat: Features
    fix: Bug fixes
  major_version_zero: false
  name: cz_conventional_commits
  tag_format: v$version
  update_changelog_on_bump: true
  version: 1.0.0
  version_scheme: semver
