---
commitizen:
  major_version_zero: false
  name: cz_conventional_commits
  tag_format: v$version
  update_changelog_on_bump: true
  version: 0.0.1
  version_scheme: semver
  change_type_map:
    feat: Features
    fix: Bug fixes
